import { z } from "zod";

export const formSchema = z.object({
  nome: z.string().min(2, "Nome deve ter no mínimo 2 caracteres"),
  email: z.string().email("Email inválido"),
  telefone: z.string().min(10, "Telefone inválido"),
  whatsapp: z.string().min(10, "Whatsapp inválido"),
  instagram: z.string().optional(),
  fotoPerfil: z.string().optional(),
  cpf: z.string().min(11, "CPF inválido"),
  rg: z.string().min(7, "RG inválido"),
  dataNascimento: z.string(),
  genero: z.enum(["masculino", "feminino", "outro", "prefiro_nao_informar"]),
  endereco: z.string(),
  cidade: z.string(),
  estado: z.string(),
  cep: z.string(),
  profissao: z.string(),
  objetivos: z.string(),
  experienciaPrevia: z.string(),
  restricoesAlimentares: z.string(),
  problemaSaude: z.string(),
  medicamentos: z.string(),
  cirurgias: z.string(),
  lesoes: z.string(),
  atividadeFisica: z.string(),
  horarioTreino: z.string(),
  observacoes: z.string(),
});