import { z } from "zod";

export const formSchema = z.object({
  nome: z.string().min(2, "Nome deve ter no mínimo 2 caracteres"),
  email: z.string().email("Email inválido"),
  telefone: z.string().min(10, "Telefone inválido"),
  whatsapp: z.string().min(10, "Whatsapp inválido"),
  instagram: z.string().optional(),
  fotoPerfil: z.string().optional(),
  cpf: z.string().min(11, "CPF inválido"),
  rg: z.string().min(7, "RG inválido"),
  dataNascimento: z.string(),
  genero: z.enum(["masculino", "feminino", "outro", "prefiro_nao_informar"]),
  endereco: z.string(),
  cidade: z.string(),
  estado: z.string(),
  cep: z.string(),
  profissao: z.string(),
  academia: z.string().min(1, "Selecione uma academia"),
  objetivos: z.string(),
  experienciaPrevia: z.string(),
  restricoesAlimentares: z.string(),
  problemaSaude: z.string(),
  medicamentos: z.string(),
  cirurgias: z.string(),
  lesoes: z.string(),
  atividadeFisica: z.string(),
  horarioTreino: z.string(),
  observacoes: z.string(),
  
  // Campos do plano
  planoId: z.string().min(1, "Selecione um plano"),
  dataInicio: z.string().min(1, "Data de início é obrigatória"),
  diaVencimento: z.string().min(1, "Dia do vencimento é obrigatório"),
  
  // Medidas
  peso: z.string().optional(),
  altura: z.string().optional(),
  pescoco: z.string().optional(),
  ombros: z.string().optional(),
  torax: z.string().optional(),
  bracoDireito: z.string().optional(),
  bracoEsquerdo: z.string().optional(),
  antebracoDireito: z.string().optional(),
  antebracoEsquerdo: z.string().optional(),
  cintura: z.string().optional(),
  quadril: z.string().optional(),
  coxaDireita: z.string().optional(),
  coxaEsquerda: z.string().optional(),
  panturrilhaDireita: z.string().optional(),
  panturrilhaEsquerda: z.string().optional(),
  
  // Fotos
  fotoFrente: z.any().optional(),
  fotoCostas: z.any().optional(),
  fotoLadoDireito: z.any().optional(),
  fotoLadoEsquerdo: z.any().optional(),
});